title: Cheng (Jonathan) Wang
logo: /assets/profile_circle.png
desctiption_text: Project portfolio of Cheng Wang, a Master's graduate at Cornell University with experience in data analysis, management consulting, and academic research. 
description:
  - phone: +81-070-8450-8094
  - email: cheng.wang@arcbricks.com
  - resume: assets/Resume.pdf
  - linkedin: https://www.linkedin.com/in/cheng-wang-1a5465219/
github: false
theme: jekyll-theme-minimal
